name = "GBCore"
uuid = "50d95318-1838-4cfa-a614-3543b4bb0509"
authors = ["jeffersonparil@gmail.com"]
version = "1.0.0-DEV"

[deps]
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Metida = "a1dec852-9fe5-11e9-361f-8d9fde67cfa2"
MixedModels = "ff71e718-51f3-5ec2-a782-8ffcbfa3c316"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
PrecompileTools = "aea7be01-6a6a-4083-8856-8a6e6704d82a"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
StatsModels = "3eaba693-59b7-5ba5-a881-562e759f1c8d"
StatsPlots = "f3b207a7-027a-5e70-b257-86293d7955fd"
UnicodePlots = "b8865327-cd53-5732-bb35-84acbb429228"

[compat]
DataFrames = "1.7.0"
Distributions = "0.25.115"
Documenter = "1.8.0"
LinearAlgebra = "1.11.0"
Metida = "0.16.3"
MixedModels = "4.28.0"
Plots = "1.40.9"
PrecompileTools = "1.2.1"
ProgressMeter = "1.10.2"
Random = "1.11.0"
Statistics = "1.11.1"
StatsBase = "0.34.4"
StatsModels = "0.7.4"
StatsPlots = "0.15.7"
UnicodePlots = "3.7.1"
julia = "1.11"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
