name = "GenomicBreedingCore"
uuid = "50d95318-1838-4cfa-a614-3543b4bb0509"
version = "0.1.1"
authors = ["jeffersonparil@gmail.com"]

[deps]
Bijectors = "76274a88-744f-5084-9051-94815aaf08c4"
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"
Clustering = "aaaa29a8-35af-508c-8bc3-b662a17a0fe5"
Combinatorics = "861a8166-3701-5b0c-9a16-15d98fcdc6aa"
CovarianceEstimation = "587fd27a-f159-11e8-2dae-1979310e6154"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Distances = "b4f34e82-e78d-54a5-968a-f98e89d6e8f7"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Lux = "b2108857-7c20-44ae-9111-449ecde12c47"
LuxCUDA = "d0bbae9a-e099-4d5b-a835-1c6931763bda"
MixedModels = "ff71e718-51f3-5ec2-a782-8ffcbfa3c316"
MultivariateStats = "6f286f6a-111f-5878-ab1e-185364afe411"
Optimisers = "3bd65402-5787-11e9-1adc-39752487f4e2"
PDMats = "90014a1f-27ba-587c-ab20-58faa44d9150"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
RDatasets = "ce6b1742-4840-55fa-b093-852dadbb1d8b"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
ScatteredInterpolation = "3f865c0f-6dca-5f4d-999b-29fe1e7e3c92"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
StatsModels = "3eaba693-59b7-5ba5-a881-562e759f1c8d"
Suppressor = "fd094767-a336-5f1f-9728-57cf17d0bbfb"
UnicodePlots = "b8865327-cd53-5732-bb35-84acbb429228"

[compat]
Bijectors = "0.15.6"
CUDA = "5.8.2"
Clustering = "0.15.8"
Combinatorics = "1.0.3"
CovarianceEstimation = "0.2.13"
DataFrames = "1.7.0"
Distances = "0.10.12"
Distributions = "0.25.115"
Documenter = "1.8.0"
JLD2 = "0.5.11, 0.6"
LinearAlgebra = "1.11.0"
Lux = "1.9.0"
LuxCUDA = "0.3.3"
MixedModels = "4.34.1, 5"
MultivariateStats = "0.10.3"
Optimisers = "0.4.6"
PDMats = "0.11.32"
ProgressMeter = "1.10.2"
RDatasets = "0.7.7, 0.8"
Random = "1.11.0"
ScatteredInterpolation = "0.3.6"
SparseArrays = "1.11.0"
Statistics = "1.11.1"
StatsBase = "0.34.5"
StatsModels = "0.7.4"
Suppressor = "0.2.8"
UnicodePlots = "3.7.1"
julia = "1.12"

[extras]
CUDA_Runtime_jll = "76a88914-d11a-5bdc-97e0-2f5a05c973a2"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
